server:
  port: 9000

spring:
  application:
    name: shop - base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  rabbitmq:
    host: 127.0.0.1
  mongo:
    host: 127.0.0.1
    port: 27017
    database: spitdb
